#   --- Import ---
import json
#   --- Import PySide6 ---
from PySide6.QtWidgets import (
    QSizePolicy,
    QLineEdit
        )
from PySide6.QtCore import (
    Qt
)

def RegisterUi(self):
    self.setObjectName('RegisterW')
    self.NameSubtitleL.setObjectName('NameSubtitleL')
    self.NameL.setObjectName('NameL')
    self.NameInfoL.setObjectName('NameInfoL')
    self.EmialSubtitleL.setObjectName('EmialSubtitleL')
    self.EmialL.setObjectName('EmialL')
    self.EmialConfirmL.setObjectName('EmialConfirmL')
    self.EmailInfoL.setObjectName('EmailInfoL')
    self.PhonenumberSubtitleL.setObjectName('PhonenumberSubtitleL')
    self.PhonenumberC.setObjectName('PhonenumberC')
    self.PhonenumberL.setObjectName('PhonenumberL')
    self.CountrySubtitleL.setObjectName('CountrySubtitleL')
    self.CountryC.setObjectName('CountryC')
    self.PasswordSubtitleL.setObjectName('PasswordSubtitleL')
    self.PasswordL.setObjectName('PasswordL')
    self.PasswordRequirementsL.setObjectName('PasswordRequirementsL')
    self.PasswordShowB.setObjectName('PasswordShowB')
    self.PasswordConfirmL.setObjectName('PasswordConfirmL')
    self.RegisterB.setObjectName('RegisterB')
    self.ExitB.setObjectName('ExitB')
    self.NameSubtitleL.setProperty('class', 'SubTitle')
    self.EmialSubtitleL.setProperty('class', 'SubTitle')
    self.PhonenumberSubtitleL.setProperty('class', 'SubTitle')
    self.CountrySubtitleL.setProperty('class', 'SubTitle')
    self.PasswordSubtitleL.setProperty('class', 'SubTitle')
    self.NameL.setProperty('class', 'InputLine')
    self.EmialL.setProperty('class', 'InputLine')
    self.EmialConfirmL.setProperty('class', 'InputLine')
    self.PhonenumberL.setProperty('class', 'InputLine')
    self.PasswordL.setProperty('class', 'InputLine')
    self.PasswordConfirmL.setProperty('class', 'InputLine')
    self.PhonenumberC.setProperty('class', 'List')
    self.CountryC.setProperty('class', 'List')
    self.NameInfoL.setProperty('class', 'InfoLabel')
    self.EmailInfoL.setProperty('class', 'InfoLabel')
    self.RegisterB.setProperty('class', 'Button')
    self.ExitB.setProperty('class', 'Button')
    
    self.Layout.addWidget(self.NameSubtitleL, 5, 5, 3, 40)
    self.Layout.addWidget(self.NameL, 10, 5, 2, 40)
    self.Layout.addWidget(self.NameInfoL, 14, 5, 3, 40)
    self.Layout.addWidget(self.EmialSubtitleL, 5, 55, 2, 40)
    self.Layout.addWidget(self.EmialL, 10, 55, 2, 40)
    self.Layout.addWidget(self.EmialConfirmL, 14, 55, 2, 40)
    self.Layout.addWidget(self.EmailInfoL, 18, 55, 2, 40)
    self.Layout.addWidget(self.CountrySubtitleL, 30, 5, 3, 40)
    self.Layout.addWidget(self.CountryC, 35, 5, 2, 40)
    self.Layout.addWidget(self.PhonenumberSubtitleL, 30, 55, 2, 40)
    self.Layout.addWidget(self.PhonenumberC, 35, 55, 2, 10)
    self.Layout.addWidget(self.PhonenumberL, 35, 65, 2, 30)
    self.Layout.addWidget(self.PasswordSubtitleL, 60, 5, 2, 90)
    self.Layout.addWidget(self.PasswordL, 65, 5, 2, 40)
    self.Layout.addWidget(self.PasswordRequirementsL, 65, 55, 6, 20)
    self.Layout.addWidget(self.PasswordShowB, 67, 80, 2, 10)
    self.Layout.addWidget(self.PasswordConfirmL, 69, 5, 2, 40)
    self.Layout.addWidget(self.RegisterB, 90, 5, 5, 40)
    self.Layout.addWidget(self.ExitB, 90, 55, 5, 40)
    self.Layout.setSpacing(0)
    self.Layout.setContentsMargins(0,0,0,0)
    for enc in range(100):
        self.Layout.setRowStretch(enc, 1)
        self.Layout.setColumnStretch(enc, 1)
    self.setLayout(self.Layout)
    self.show()
    self.NameInfoL.hide()
    self.EmailInfoL.hide()
    self.NameSubtitleL.setAlignment(Qt.AlignCenter)
    self.NameInfoL.setAlignment(Qt.AlignCenter)
    self.EmialSubtitleL.setAlignment(Qt.AlignCenter)
    self.EmialL.setAlignment(Qt.AlignCenter)
    self.PhonenumberSubtitleL.setAlignment(Qt.AlignCenter)
    self.CountrySubtitleL.setAlignment(Qt.AlignCenter)
    self.PasswordSubtitleL.setAlignment(Qt.AlignCenter)
    self.PasswordRequirementsL.setAlignment(Qt.AlignCenter)
    self.PasswordL.setEchoMode(QLineEdit.Password)
    self.PasswordConfirmL.setEchoMode(QLineEdit.Password)
    self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.NameSubtitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.NameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.NameInfoL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.EmialSubtitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.EmialL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.EmialConfirmL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.EmailInfoL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PhonenumberSubtitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PhonenumberC.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PhonenumberL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CountrySubtitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CountryC.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PasswordSubtitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PasswordL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PasswordRequirementsL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PasswordShowB.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PasswordConfirmL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.RegisterB.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ExitB.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

def RegisterReloadStyle(self):
    t = self.Theme
    m = open(f'{self.Path}/assets/CSS/RegisterMain.css').read()
    c = open(f'{self.Path}/assets/CSS/Register{t}.css').read()
    self.setStyleSheet(m+c)

def RegisterRetranslate(self):
    l = self.Language
    t = json.load(open(f'{self.Path}/assets/JSON/RegisterTranslate.json', 'r', encoding='utf-8'))
    self.NameSubtitleL.setText(t['NameSubtitleL'][l])
    self.NameL.setPlaceholderText(t['NameL'][l])
    self.EmialSubtitleL.setText(t['EmialSubtitleL'][l])
    self.EmialL.setPlaceholderText(t['EmialL'][l])
    self.EmialConfirmL.setPlaceholderText(t['EmialConfirmL'][l])
    self.PhonenumberSubtitleL.setText(t['PhonenumberSubtitleL'][l])
    self.PhonenumberC.addItems(self.GetPhonePrefixF())
    self.PhonenumberL.setPlaceholderText(t['PhonenumberL'][0][l])
    self.CountrySubtitleL.setText(t['CountrySubtitleL'][l])
    self.CountryC.addItems(self.GetCountriesF())
    self.PasswordSubtitleL.setText(t['PasswordSubtitleL'][l])
    self.PasswordL.setPlaceholderText(t['PasswordL'][l])
    self.PasswordRequirementsL.setText(t['PasswordRequirementsL'][0][l])
    self.PasswordShowB.setText(t['PasswordShowB'][1][l])
    self.PasswordConfirmL.setPlaceholderText(t['PasswordConfirmL'][l])
    self.RegisterB.setText(t['RegisterB'][0][l])
    self.ExitB.setText(t['ExitB'][l])
