#   --- Improt ---
import json
from PyQt5.QtWidgets import (
    QSizePolicy
)
from PyQt5.QtCore import (
    Qt,
    QSize
)
from PyQt5.QtGui import (
    QPixmap,
    QIcon,
    QPainter
)
from PyQt5.QtSvg import (
    QSvgRenderer
)

def CountryUi(self):
    self.setObjectName('ObjectInfoS')
    self.WidgetW.setObjectName('WidgetW')
    self.IconL.setObjectName('IconL')
    self.NameL.setObjectName('NameL')
    self.IsoL.setObjectName('IsoL')
    self.ContinentL.setObjectName('ContinentL')
    self.SubRegion.setObjectName('SubRegion')
    self.InfoW.setObjectName('InfoW')
    self.InfoTitleL.setObjectName('InfoTitleL')
    self.CurrencyCodeNameL.setObjectName('CurrencyCodeNameL')
    self.CurrencyCodeValueL.setObjectName('CurrencyCodeValueL')
    self.CurrencyNameNameL.setObjectName('CurrencyNameNameL')
    self.CurrencyNameValueL.setObjectName('CurrencyNameValueL')
    self.CapitalCityNameL.setObjectName('CapitalCityNameL')
    self.CapitalCityValueL.setObjectName('CapitalCityValueL')
    self.TimezoneNameL.setObjectName('TimezoneNameL')
    self.TimezoneValueL.setObjectName('TimezoneValueL')
    self.ExchangeNameNameL.setObjectName('ExchangeNameNameL')
    self.ExchangeNameValueL.setObjectName('ExchangeNameValueL')
    self.ExchangeCodeMicNameL.setObjectName('ExchangeCodeMicNameL')
    self.ExchangeCodeMicValueL.setObjectName('ExchangeCodeMicValueL')
    self.ExchangeCountryNameL.setObjectName('ExchangeCountryNameL')
    self.ExchangeCountryValueL.setObjectName('ExchangeCountryValueL')
    self.ExchangeTimezoneNameL.setObjectName('ExchangeTimezoneNameL')
    self.ExchangeTimezoneValueL.setObjectName('ExchangeTimezoneValueL')
    self.TradingHoursNameL.setObjectName('TradingHoursNameL')
    self.TradingHoursValueL.setObjectName('TradingHoursValueL')
    self.CurrencyNameL.setObjectName('CurrencyNameL')
    self.CurrencyValueL.setObjectName('CurrencyValueL')
    self.CurrencyCodeNameL.setProperty('class', 'Name')
    self.CurrencyNameNameL.setProperty('class', 'Name')
    self.CapitalCityNameL.setProperty('class', 'Name')
    self.TimezoneNameL.setProperty('class', 'Name')
    self.ExchangeNameNameL.setProperty('class', 'Name')
    self.ExchangeCodeMicNameL.setProperty('class', 'Name')
    self.ExchangeCountryNameL.setProperty('class', 'Name')
    self.ExchangeTimezoneNameL.setProperty('class', 'Name')
    self.TradingHoursNameL.setProperty('class', 'Name')
    self.CurrencyNameL.setProperty('class', 'Name')
    self.CurrencyCodeValueL.setProperty('class', 'Value')
    self.CurrencyNameValueL.setProperty('class', 'Value')
    self.CapitalCityValueL.setProperty('class', 'Value')
    self.TimezoneValueL.setProperty('class', 'Value')
    self.ExchangeNameValueL.setProperty('class', 'Value')
    self.ExchangeCodeMicValueL.setProperty('class', 'Value')
    self.ExchangeCountryValueL.setProperty('class', 'Value')
    self.ExchangeTimezoneValueL.setProperty('class', 'Value')
    self.TradingHoursValueL.setProperty('class', 'Value')
    self.CurrencyValueL.setProperty('class', 'Value')
    self.InfoL.addWidget(self.InfoTitleL, 0, 0, 1, 100)
    self.InfoL.addWidget(self.CurrencyCodeNameL, 1, 0, 1, 50)
    self.InfoL.addWidget(self.CurrencyCodeValueL, 1, 50, 1, 50)
    self.InfoL.addWidget(self.CurrencyNameNameL, 2, 0, 1, 50)
    self.InfoL.addWidget(self.CurrencyNameValueL, 2, 50, 1, 50)
    self.InfoL.addWidget(self.CapitalCityNameL, 3, 0, 1, 50)
    self.InfoL.addWidget(self.CapitalCityValueL, 3, 50, 1, 50)
    self.InfoL.addWidget(self.TimezoneNameL, 4, 0, 1, 50)
    self.InfoL.addWidget(self.TimezoneValueL, 4, 50, 1, 50)
    self.InfoL.addWidget(self.ExchangeNameNameL, 5, 0, 1, 50)
    self.InfoL.addWidget(self.ExchangeNameValueL, 5, 50, 1, 50)
    self.InfoL.addWidget(self.ExchangeCodeMicNameL, 6, 0, 1, 50)
    self.InfoL.addWidget(self.ExchangeCodeMicValueL, 6, 50, 1, 50)
    self.InfoL.addWidget(self.ExchangeCountryNameL, 7, 0, 1, 50)
    self.InfoL.addWidget(self.ExchangeCountryValueL, 7, 50, 1, 50)
    self.InfoL.addWidget(self.ExchangeTimezoneNameL, 8, 0, 1, 50)
    self.InfoL.addWidget(self.ExchangeTimezoneValueL, 8, 50, 1, 50)
    self.InfoL.addWidget(self.TradingHoursNameL, 9, 0, 1, 50)
    self.InfoL.addWidget(self.TradingHoursValueL, 9, 50, 1, 50)
    self.InfoL.addWidget(self.CurrencyNameL, 10, 0, 1, 50)
    self.InfoL.addWidget(self.CurrencyValueL, 10, 50, 1, 50)
    self.InfoL.setSpacing(0)
    self.InfoL.setContentsMargins(0,0,0,0)
    for i in range(100):
        self.InfoL.setColumnStretch(i, 1)
    self.InfoW.setLayout(self.InfoL)
    self.LayoutL.addWidget(self.IconL, 0, 30, 1, 40)
    self.LayoutL.addWidget(self.NameL, 1, 0, 1, 100)
    self.LayoutL.addWidget(self.IsoL, 2, 0, 1, 50)
    self.LayoutL.addWidget(self.ContinentL, 3, 0, 1, 50)
    self.LayoutL.addWidget(self.SubRegion, 3, 50, 1, 50)
    self.LayoutL.addWidget(self.InfoW, 4, 0, 1, 100)
    self.LayoutL.setSpacing(0)
    self.LayoutL.setContentsMargins(0,0,0,0)
    for i in range(100):
        self.LayoutL.setColumnStretch(i, 1)
    self.WidgetW.setLayout(self.LayoutL)
    self.show()
    self.setWidget(self.WidgetW)
    self.setWidgetResizable(True)
    self.IconL.setAlignment(Qt.AlignCenter)
    self.NameL.setAlignment(Qt.AlignCenter)
    self.IsoL.setAlignment(Qt.AlignCenter)
    self.ContinentL.setAlignment(Qt.AlignCenter)
    self.SubRegion.setAlignment(Qt.AlignCenter)
    self.InfoTitleL.setAlignment(Qt.AlignCenter)
    self.CurrencyCodeNameL.setAlignment(Qt.AlignCenter)
    self.CurrencyCodeValueL.setAlignment(Qt.AlignCenter)
    self.CurrencyNameNameL.setAlignment(Qt.AlignCenter)
    self.CurrencyNameValueL.setAlignment(Qt.AlignCenter)
    self.CapitalCityNameL.setAlignment(Qt.AlignCenter)
    self.CapitalCityValueL.setAlignment(Qt.AlignCenter)
    self.TimezoneNameL.setAlignment(Qt.AlignCenter)
    self.TimezoneValueL.setAlignment(Qt.AlignCenter)
    self.ExchangeNameNameL.setAlignment(Qt.AlignCenter)
    self.ExchangeNameValueL.setAlignment(Qt.AlignCenter)
    self.ExchangeCodeMicNameL.setAlignment(Qt.AlignCenter)
    self.ExchangeCodeMicValueL.setAlignment(Qt.AlignCenter)
    self.ExchangeCountryNameL.setAlignment(Qt.AlignCenter)
    self.ExchangeCountryValueL.setAlignment(Qt.AlignCenter)
    self.ExchangeTimezoneNameL.setAlignment(Qt.AlignCenter)
    self.ExchangeTimezoneValueL.setAlignment(Qt.AlignCenter)
    self.TradingHoursNameL.setAlignment(Qt.AlignCenter)
    self.TradingHoursValueL.setAlignment(Qt.AlignCenter)
    self.CurrencyNameL.setAlignment(Qt.AlignCenter)
    self.CurrencyValueL.setAlignment(Qt.AlignCenter)
    self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.WidgetW.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.IconL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.NameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.IsoL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ContinentL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.SubRegion.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.InfoW.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.InfoTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CurrencyCodeNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CurrencyCodeValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CurrencyNameNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CurrencyNameValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CapitalCityNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CapitalCityValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.TimezoneNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.TimezoneValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ExchangeNameNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ExchangeNameValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ExchangeCodeMicNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ExchangeCodeMicValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ExchangeCountryNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ExchangeCountryValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ExchangeTimezoneNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ExchangeTimezoneValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.TradingHoursNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.TradingHoursValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CurrencyNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CurrencyValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

def CountryReloadStyle(self):
    t = self.Theme
    m = open(f'{self.Path}/APP_FILES/PYTHON/ObjectInfo/BCountry.css').read()
    c = open(f'{self.Path}/APP_FILES/PYTHON/ObjectInfo/BCountry{t}.css').read()
    self.setStyleSheet(m+c)

def CountryRetranslate(self):
    t = json.load(open(f'{self.Path}/APP_FILES/PYTHON/ObjectInfo/CCountryTranslate.json', 'r'))
    l = self.Language
    self.InfoTitleL.setText(t['InfoTitleL'][l])
    self.CurrencyCodeNameL.setText(t['CurrencyCodeNameL'][l]+':')
    self.CurrencyNameNameL.setText(t['CurrencyNameNameL'][l]+':')
    self.CapitalCityNameL.setText(t['CapitalCityNameL'][l]+':')
    self.TimezoneNameL.setText(t['TimezoneNameL'][l]+':')
    self.ExchangeNameNameL.setText(t['ExchangeNameNameL'][l]+':')
    self.ExchangeCodeMicNameL.setText(t['ExchangeCodeMicNameL'][l]+':')
    self.ExchangeCountryNameL.setText(t['ExchangeCountryNameL'][l]+':')
    self.ExchangeTimezoneNameL.setText(t['ExchangeTimezoneNameL'][l]+':')
    self.TradingHoursNameL.setText(t['TradingHoursNameL'][l]+':')
    self.CurrencyNameL.setText(t['CurrencyNameL'][l]+':')

def MarketUi(self):
    self.setObjectName('ObjectInfoS')
    self.WidgetW.setObjectName('WidgetW')
    self.IconL.setObjectName('IconL')
    self.TickerL.setObjectName('TickerL')
    self.NameL.setObjectName('NameL')
    self.MicCodeL.setObjectName('MicCodeL')
    self.OperatingMicL.setObjectName('OperatingMicL')
    self.CountryL.setObjectName('CountryL')
    self.InfoW.setObjectName('InfoW')
    self.InfoTitleL.setObjectName('InfoTitleL')
    self.FoundedYearNameL.setObjectName('FoundedYearNameL')
    self.FoundedYearValueL.setObjectName('FoundedYearValueL')
    self.CityNameL.setObjectName('CityNameL')
    self.CityValueL.setObjectName('CityValueL')
    self.TimezoneNameL.setObjectName('TimezoneNameL')
    self.TimezoneValueL.setObjectName('TimezoneValueL')
    self.CurrencyNameL.setObjectName('CurrencyNameL')
    self.CurrencyValueL.setObjectName('CurrencyValueL')
    self.WebsiteNameL.setObjectName('WebsiteNameL')
    self.WebsiteValueL.setObjectName('WebsiteValueL')
    self.MarketTypesNameL.setObjectName('MarketTypesNameL')
    self.MarketTypesValueL.setObjectName('MarketTypesValueL')
    self.TradingSessionTitleL.setObjectName('TradingSessionTitleL')
    self.PreMarketNameL.setObjectName('PreMarketNameL')
    self.PreMarketValueL.setObjectName('PreMarketValueL')
    self.OpenNameL.setObjectName('OpenNameL')
    self.OpenValueL.setObjectName('OpenValueL')
    self.CloseNameL.setObjectName('CloseNameL')
    self.CloseValueL.setObjectName('CloseValueL')
    self.CalendarTitleL.setObjectName('CalendarTitleL')
    self.FreeDaysNameL.setObjectName('FreeDaysNameL')
    self.FreeDaysValueL.setObjectName('FreeDaysValueL')
    self.ExchangeStructureTitleL.setObjectName('ExchangeStructureTitleL')
    self.InstrumentTypesNameL.setObjectName('InstrumentTypesNameL')
    self.InstrumentTypesValueL.setObjectName('InstrumentTypesValueL')
    self.MarketSegmentsNameL.setObjectName('MarketSegmentsNameL')
    self.MarketSegmentsValueL.setObjectName('MarketSegmentsValueL')
    self.RegulatorsNameL.setObjectName('RegulatorsNameL')
    self.RegulatorsValueL.setObjectName('RegulatorsValueL')
    self.TradingSystemsNameL.setObjectName('TradingSystemsNameL')
    self.TradingSystemsValueL.setObjectName('TradingSystemsValueL')
    self.InfoTitleL.setProperty('class', 'SubTitle')
    self.TradingSessionTitleL.setProperty('class', 'SubTitle')
    self.CalendarTitleL.setProperty('class', 'SubTitle')
    self.ExchangeStructureTitleL.setProperty('class', 'SubTitle')
    self.FoundedYearNameL.setProperty('class', 'Name')
    self.CityNameL.setProperty('class', 'Name')
    self.TimezoneNameL.setProperty('class', 'Name')
    self.CurrencyNameL.setProperty('class', 'Name')
    self.WebsiteNameL.setProperty('class', 'Name')
    self.MarketTypesNameL.setProperty('class', 'Name')
    self.PreMarketNameL.setProperty('class', 'Name')
    self.OpenNameL.setProperty('class', 'Name')
    self.CloseNameL.setProperty('class', 'Name')
    self.FreeDaysNameL.setProperty('class', 'Name')
    self.InstrumentTypesNameL.setProperty('class', 'Name')
    self.MarketSegmentsNameL.setProperty('class', 'Name')
    self.RegulatorsNameL.setProperty('class', 'Name')
    self.TradingSystemsNameL.setProperty('class', 'Name')
    self.FoundedYearValueL.setProperty('class', 'Value')
    self.TradingSystemsValueL.setProperty('class', 'Value')
    self.CityValueL.setProperty('class', 'Value')
    self.TimezoneValueL.setProperty('class', 'Value')
    self.CurrencyValueL.setProperty('class', 'Value')
    self.WebsiteValueL.setProperty('class', 'Value')
    self.MarketTypesValueL.setProperty('class', 'Value')
    self.PreMarketValueL.setProperty('class', 'Value')
    self.OpenValueL.setProperty('class', 'Value')
    self.CloseValueL.setProperty('class', 'Value')
    self.FreeDaysValueL.setProperty('class', 'Value')
    self.InstrumentTypesValueL.setProperty('class', 'Value')
    self.MarketSegmentsValueL.setProperty('class', 'Value')
    self.RegulatorsValueL.setProperty('class', 'Value')
    self.InfoL.addWidget(self.InfoTitleL, 0, 0, 1, 100)
    self.InfoL.addWidget(self.FoundedYearNameL, 1, 0, 1, 50)
    self.InfoL.addWidget(self.FoundedYearValueL,1, 50, 1, 50)
    self.InfoL.addWidget(self.CityNameL, 2, 0, 1, 50)
    self.InfoL.addWidget(self.CityValueL, 2, 50, 1, 50)
    self.InfoL.addWidget(self.TimezoneNameL, 3, 0, 1, 50)
    self.InfoL.addWidget(self.TimezoneValueL, 3, 50, 1, 50)
    self.InfoL.addWidget(self.CurrencyNameL, 4, 0, 1, 50)
    self.InfoL.addWidget(self.CurrencyValueL, 4, 50, 1, 50)
    self.InfoL.addWidget(self.WebsiteNameL, 5, 0, 1, 50)
    self.InfoL.addWidget(self.WebsiteValueL, 5, 50, 1, 50)
    self.InfoL.addWidget(self.MarketTypesNameL, 6, 0, 1, 50)
    self.InfoL.addWidget(self.MarketTypesValueL, 6, 50, 1, 50)
    self.InfoL.addWidget(self.TradingSessionTitleL, 7, 0, 1, 100)
    self.InfoL.addWidget(self.PreMarketNameL, 8, 0, 1, 50)
    self.InfoL.addWidget(self.PreMarketValueL, 8, 50, 1, 50)
    self.InfoL.addWidget(self.OpenNameL, 9, 0, 1, 50)
    self.InfoL.addWidget(self.OpenValueL, 9, 50, 1, 50)
    self.InfoL.addWidget(self.CloseNameL, 10, 0, 1, 50)
    self.InfoL.addWidget(self.CloseValueL, 10, 50, 1, 50)
    self.InfoL.addWidget(self.CalendarTitleL, 11, 0, 1, 100)
    self.InfoL.addWidget(self.FreeDaysNameL, 12, 0, 1, 50)
    self.InfoL.addWidget(self.FreeDaysValueL, 12, 50, 1, 50)
    self.InfoL.addWidget(self.ExchangeStructureTitleL, 13, 0, 1, 100)
    self.InfoL.addWidget(self.InstrumentTypesNameL, 14, 0, 1, 50)
    self.InfoL.addWidget(self.InstrumentTypesValueL, 14, 50, 1, 50)
    self.InfoL.addWidget(self.MarketSegmentsNameL, 15, 0, 1, 50)
    self.InfoL.addWidget(self.MarketSegmentsValueL, 15, 50, 1, 50)
    self.InfoL.addWidget(self.RegulatorsNameL, 16, 0, 1, 50)
    self.InfoL.addWidget(self.RegulatorsValueL, 16, 50, 1, 50)
    self.InfoL.addWidget(self.TradingSystemsNameL, 17, 0, 1, 50)
    self.InfoL.addWidget(self.TradingSystemsValueL, 17, 50, 1, 50)
    self.InfoL.setSpacing(0)
    self.InfoL.setContentsMargins(0,0,0,0)
    for i in range(100):
        self.InfoL.setColumnStretch(i, 1)
    self.InfoW.setLayout(self.InfoL)
    self.LayoutL.addWidget(self.IconL, 0, 30, 1, 40)
    self.LayoutL.addWidget(self.TickerL, 1, 0, 1, 100)
    self.LayoutL.addWidget(self.NameL, 2, 0, 1, 100)
    self.LayoutL.addWidget(self.MicCodeL, 3, 0, 1, 50)
    self.LayoutL.addWidget(self.OperatingMicL, 3, 50, 1, 50)
    self.LayoutL.addWidget(self.CountryL, 4, 0, 1, 100)
    self.LayoutL.addWidget(self.InfoW, 5, 0, 1, 100)
    self.LayoutL.setSpacing(0)
    self.LayoutL.setContentsMargins(0,0,0,0)
    for i in range(100):
        self.LayoutL.setColumnStretch(i, 1)
    self.WidgetW.setLayout(self.LayoutL)
    self.show()
    self.setWidget(self.WidgetW)
    self.setWidgetResizable(True)
    self.IconL.setAlignment(Qt.AlignCenter)
    self.TickerL.setAlignment(Qt.AlignCenter)
    self.NameL.setAlignment(Qt.AlignCenter)
    self.MicCodeL.setAlignment(Qt.AlignCenter)
    self.OperatingMicL.setAlignment(Qt.AlignCenter)
    self.CountryL.setAlignment(Qt.AlignCenter)
    self.InfoTitleL.setAlignment(Qt.AlignCenter)
    self.FoundedYearNameL.setAlignment(Qt.AlignCenter)
    self.FoundedYearValueL.setAlignment(Qt.AlignCenter)
    self.CityNameL.setAlignment(Qt.AlignCenter)
    self.CityValueL.setAlignment(Qt.AlignCenter)
    self.TimezoneNameL.setAlignment(Qt.AlignCenter)
    self.TimezoneValueL.setAlignment(Qt.AlignCenter)
    self.CurrencyNameL.setAlignment(Qt.AlignCenter)
    self.CurrencyValueL.setAlignment(Qt.AlignCenter)
    self.WebsiteNameL.setAlignment(Qt.AlignCenter)
    self.WebsiteValueL.setAlignment(Qt.AlignCenter)
    self.MarketTypesNameL.setAlignment(Qt.AlignCenter)
    self.MarketTypesValueL.setAlignment(Qt.AlignCenter)
    self.TradingSessionTitleL.setAlignment(Qt.AlignCenter)
    self.PreMarketNameL.setAlignment(Qt.AlignCenter)
    self.PreMarketValueL.setAlignment(Qt.AlignCenter)
    self.OpenNameL.setAlignment(Qt.AlignCenter)
    self.OpenValueL.setAlignment(Qt.AlignCenter)
    self.CloseNameL.setAlignment(Qt.AlignCenter)
    self.CloseValueL.setAlignment(Qt.AlignCenter)
    self.CalendarTitleL.setAlignment(Qt.AlignCenter)
    self.FreeDaysNameL.setAlignment(Qt.AlignCenter)
    self.FreeDaysValueL.setAlignment(Qt.AlignCenter)
    self.ExchangeStructureTitleL.setAlignment(Qt.AlignCenter)
    self.InstrumentTypesNameL.setAlignment(Qt.AlignCenter)
    self.InstrumentTypesValueL.setAlignment(Qt.AlignCenter)
    self.MarketSegmentsNameL.setAlignment(Qt.AlignCenter)
    self.MarketSegmentsValueL.setAlignment(Qt.AlignCenter)
    self.RegulatorsNameL.setAlignment(Qt.AlignCenter)
    self.RegulatorsValueL.setAlignment(Qt.AlignCenter)
    self.TradingSystemsNameL.setAlignment(Qt.AlignCenter)
    self.TradingSystemsValueL.setAlignment(Qt.AlignCenter)
    self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.WidgetW.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.IconL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.TickerL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.NameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.MicCodeL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.OperatingMicL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CountryL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.InfoW.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.InfoTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.FoundedYearNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.FoundedYearValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CityNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CityValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.TimezoneNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.TimezoneValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CurrencyNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CurrencyValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.WebsiteNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.WebsiteValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.MarketTypesNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.MarketTypesValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.TradingSessionTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PreMarketNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PreMarketValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.OpenNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.OpenValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CloseNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CloseValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CalendarTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.FreeDaysNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.FreeDaysValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ExchangeStructureTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.InstrumentTypesNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.InstrumentTypesValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.MarketSegmentsNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.MarketSegmentsValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.RegulatorsNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.RegulatorsValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.TradingSystemsNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.TradingSystemsValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

def MarketReloadStyle(self):
    t = self.Theme
    m = open(f'{self.Path}/APP_FILES/PYTHON/ObjectInfo/BMarket.css').read()
    c = open(f'{self.Path}/APP_FILES/PYTHON/ObjectInfo/BMarket{t}.css').read()
    self.setStyleSheet(m+c)

def MarketRetranslate(self):
    t = json.load(open(f'{self.Path}/APP_FILES/PYTHON/ObjectInfo/CMarketTranslate.json', 'r'))
    l = self.Language
    self.InfoTitleL.setText(t['InfoTitleL'][l]+':')
    self.FoundedYearNameL.setText(t['FoundedYearNameL'][l]+':')
    self.CityNameL.setText(t['CityNameL'][l]+':')
    self.TimezoneNameL.setText(t['TimezoneNameL'][l]+':')
    self.CurrencyNameL.setText(t['CurrencyNameL'][l]+':')
    self.WebsiteNameL.setText(t['WebsiteNameL'][l]+':')
    self.MarketTypesNameL.setText(t['MarketTypesNameL'][l]+':')
    self.TradingSessionTitleL.setText(t['TradingSessionTitleL'][l]+':')
    self.PreMarketNameL.setText(t['PreMarketNameL'][l]+':')
    self.OpenNameL.setText(t['OpenNameL'][l]+':')
    self.CloseNameL.setText(t['CloseNameL'][l]+':')
    self.CalendarTitleL.setText(t['CalendarTitleL'][l]+':')
    self.FreeDaysNameL.setText(t['FreeDaysNameL'][l]+':')
    self.ExchangeStructureTitleL.setText(t['ExchangeStructureTitleL'][l]+':')
    self.InstrumentTypesNameL.setText(t['InstrumentTypesNameL'][l]+':')
    self.MarketSegmentsNameL.setText(t['MarketSegmentsNameL'][l]+':')
    self.RegulatorsNameL.setText(t['RegulatorsNameL'][l]+':')
    self.TradingSystemsNameL.setText(t['TradingSystemsNameL'][l]+':')

def StockUi(self):
    self.setObjectName('ObjectInfoS')
    self.WidgetW.setObjectName('WidgetW')
    self.IconL.setObjectName('IconL')
    self.TickerL.setObjectName('TickerL')
    self.NameL.setObjectName('NameL')
    self.MarketL.setObjectName('MarketL')
    self.CountryL.setObjectName('CountryL')
    self.InfoW.setObjectName('InfoW')
    self.InfoTitleL.setObjectName('InfoTitleL')
    self.ActivityNameL.setObjectName('ActivityNameL')
    self.ActivityValueL.setObjectName('ActivityValueL')
    self.IndustryNameL.setObjectName('IndustryNameL')
    self.IndustryValueL.setObjectName('IndustryValueL')
    self.DateEstablishNameL.setObjectName('DateEstablishNameL')
    self.DateEstablishValueL.setObjectName('DateEstablishValueL')
    self.EmployesNameL.setObjectName('EmployesNameL')
    self.EmployesValueL.setObjectName('EmployesValueL')
    self.WebNameL.setObjectName('WebNameL')
    self.WebValueL.setObjectName('WebValueL')
    self.AdresNameL.setObjectName('AdresNameL')
    self.AdresValueL.setObjectName('AdresValueL')
    self.ManagmentTitleL.setObjectName('ManagmentTitleL')
    self.CEONameL.setObjectName('CEONameL')
    self.CEOValueL.setObjectName('CEOValueL')
    self.CFONameL.setObjectName('CFONameL')
    self.CFOValueL.setObjectName('CFOValueL')
    self.ManagmentNameL.setObjectName('ManagmentNameL')
    self.ManagmentValueL.setObjectName('ManagmentValueL')
    self.SupervisoryBoardNameL.setObjectName('SupervisoryBoardNameL')
    self.SupervisoryBoardValueL.setObjectName('SupervisoryBoardValueL')
    self.InfoTitleL.setProperty('class', 'SubTitle')
    self.ManagmentTitleL.setProperty('class', 'SubTitle')
    self.ActivityNameL.setProperty('class', 'Name')
    self.IndustryNameL.setProperty('class', 'Name')
    self.DateEstablishNameL.setProperty('class', 'Name')
    self.EmployesNameL.setProperty('class', 'Name')
    self.WebNameL.setProperty('class', 'Name')
    self.AdresNameL.setProperty('class', 'Name')
    self.CEONameL.setProperty('class', 'Name')
    self.CFONameL.setProperty('class', 'Name')
    self.ManagmentNameL.setProperty('class', 'Name')
    self.SupervisoryBoardNameL.setProperty('class', 'Name')
    self.ActivityValueL.setProperty('class', 'Value')
    self.IndustryValueL.setProperty('class', 'Value')
    self.DateEstablishValueL.setProperty('class', 'Value')
    self.EmployesValueL.setProperty('class', 'Value')
    self.WebValueL.setProperty('class', 'Value')
    self.AdresValueL.setProperty('class', 'Value')
    self.CEOValueL.setProperty('class', 'Value')
    self.CFOValueL.setProperty('class', 'Value')
    self.ManagmentValueL.setProperty('class', 'Value')
    self.SupervisoryBoardValueL.setProperty('class', 'Value')
    self.InfoL.addWidget(self.InfoTitleL, 0, 0, 1, 100)
    self.InfoL.addWidget(self.ActivityNameL, 1, 0, 1, 50)
    self.InfoL.addWidget(self.ActivityValueL, 1, 50, 1,50)
    self.InfoL.addWidget(self.IndustryNameL, 2, 0, 1, 50)
    self.InfoL.addWidget(self.IndustryValueL, 2, 50, 1, 50)
    self.InfoL.addWidget(self.DateEstablishNameL, 3, 0, 1, 50)
    self.InfoL.addWidget(self.DateEstablishValueL,3, 50, 1, 50)
    self.InfoL.addWidget(self.EmployesNameL, 4, 0, 1, 50)
    self.InfoL.addWidget(self.EmployesValueL, 4, 50, 1, 50)
    self.InfoL.addWidget(self.WebNameL, 5, 0, 1, 50)
    self.InfoL.addWidget(self.WebValueL, 5, 50, 1, 50)
    self.InfoL.addWidget(self.AdresNameL, 6, 0, 1, 50)
    self.InfoL.addWidget(self.AdresValueL, 6, 50 ,1, 50)
    self.InfoL.addWidget(self.ManagmentTitleL, 7, 0, 1, 100)
    self.InfoL.addWidget(self.CEONameL, 8, 0, 1, 50)
    self.InfoL.addWidget(self.CEOValueL, 8, 50, 1, 50)
    self.InfoL.addWidget(self.CFONameL, 9, 0, 1, 50)
    self.InfoL.addWidget(self.CFOValueL, 9, 50, 1, 50)
    self.InfoL.addWidget(self.ManagmentNameL, 10, 0, 1, 50)
    self.InfoL.addWidget(self.ManagmentValueL, 10, 50, 1, 50)
    self.InfoL.addWidget(self.SupervisoryBoardNameL, 11, 0, 1, 50)
    self.InfoL.addWidget(self.SupervisoryBoardValueL, 11, 50, 1, 50)
    self.InfoL.setSpacing(0)
    self.InfoL.setContentsMargins(0,0,0,0)
    for i in range(100):
        self.InfoL.setColumnStretch(i, 1)
    self.InfoW.setLayout(self.InfoL)
    self.LayoutL.addWidget(self.IconL, 0, 30, 1, 40)
    self.LayoutL.addWidget(self.TickerL, 1, 0, 1, 100)
    self.LayoutL.addWidget(self.NameL, 2, 0, 1, 100)
    self.LayoutL.addWidget(self.MarketL, 3, 0, 1, 50)
    self.LayoutL.addWidget(self.CountryL,3, 50, 1, 50)
    self.LayoutL.addWidget(self.InfoW, 4, 0, 1, 100)
    self.LayoutL.setSpacing(0)
    self.LayoutL.setContentsMargins(0,0,0,0)
    for i in range(100):
        self.LayoutL.setColumnStretch(i, 1)
    self.WidgetW.setLayout(self.LayoutL)
    self.show()
    self.setWidget(self.WidgetW)
    self.setWidgetResizable(True)
    self.IconL.setAlignment(Qt.AlignCenter)
    self.TickerL.setAlignment(Qt.AlignCenter)
    self.NameL.setAlignment(Qt.AlignCenter)
    self.MarketL.setAlignment(Qt.AlignCenter)
    self.CountryL.setAlignment(Qt.AlignCenter)
    self.InfoTitleL.setAlignment(Qt.AlignCenter)
    self.ActivityNameL.setAlignment(Qt.AlignCenter)
    self.ActivityValueL.setAlignment(Qt.AlignCenter)
    self.IndustryNameL.setAlignment(Qt.AlignCenter)
    self.IndustryValueL.setAlignment(Qt.AlignCenter)
    self.DateEstablishNameL.setAlignment(Qt.AlignCenter)
    self.DateEstablishValueL.setAlignment(Qt.AlignCenter)
    self.EmployesNameL.setAlignment(Qt.AlignCenter)
    self.EmployesValueL.setAlignment(Qt.AlignCenter)
    self.WebNameL.setAlignment(Qt.AlignCenter)
    self.WebValueL.setAlignment(Qt.AlignCenter)
    self.AdresNameL.setAlignment(Qt.AlignCenter)
    self.AdresValueL.setAlignment(Qt.AlignCenter)
    self.ManagmentTitleL.setAlignment(Qt.AlignCenter)
    self.CEONameL.setAlignment(Qt.AlignCenter)
    self.CEOValueL.setAlignment(Qt.AlignCenter)
    self.CFONameL.setAlignment(Qt.AlignCenter)
    self.CFOValueL.setAlignment(Qt.AlignCenter)
    self.ManagmentNameL.setAlignment(Qt.AlignCenter)
    self.ManagmentValueL.setAlignment(Qt.AlignCenter)
    self.SupervisoryBoardNameL.setAlignment(Qt.AlignCenter)
    self.SupervisoryBoardValueL.setAlignment(Qt.AlignCenter)
    self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.WidgetW.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.IconL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.TickerL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.NameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.MarketL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CountryL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.InfoW.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.InfoTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ActivityNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ActivityValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.IndustryNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.IndustryValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.DateEstablishNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.DateEstablishValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.EmployesNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.EmployesValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.WebNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.WebValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.AdresNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.AdresValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ManagmentTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CEONameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CEOValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CFONameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CFOValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ManagmentNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ManagmentValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.SupervisoryBoardNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.SupervisoryBoardValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

def StockReloadStyle(self):
    t = self.Theme
    m = open(f'{self.Path}/APP_FILES/PYTHON/ObjectInfo/BStock.css').read()
    c = open(f'{self.Path}/APP_FILES/PYTHON/ObjectInfo/BStock{t}.css').read()
    self.setStyleSheet(m+c)

def StockRetranslate(self):
    t = json.load(open(f'{self.Path}/APP_FILES/PYTHON/ObjectInfo/CStockTranslate.json', 'r'))
    l = self.Language
    self.InfoTitleL.setText(t['InfoTitleL'][l])
    self.ActivityNameL.setText(t['ActivityNameL'][l]+':')
    self.IndustryNameL.setText(t['IndustryNameL'][l]+':')
    self.DateEstablishNameL.setText(t['DateEstablishNameL'][l]+':')
    self.EmployesNameL.setText(t['EmployesNameL'][l]+':')
    self.WebNameL.setText(t['WebNameL'][l]+':')
    self.AdresNameL.setText(t['AdresNameL'][l]+':')
    self.ManagmentTitleL.setText(t['ManagmentTitleL'][l])
    self.CEONameL.setText(t['CEONameL'][l]+':')
    self.CFONameL.setText(t['CFONameL'][l]+':')
    self.ManagmentNameL.setText(t['ManagmentNameL'][l]+':')
    self.SupervisoryBoardNameL.setText(t['SupervisoryBoardNameL'][l]+':')
