""" Import packages """
import json
""" Import PyQt5 packages """
from PyQt5.QtWidgets import (
    QSizePolicy
)
from PyQt5.QtCore import (
    Qt,
    QSize
)
from PyQt5.QtGui import (
    QIcon,
    QPixmap,
    QPainter
)
from PyQt5.QtSvg import (
    QSvgRenderer
)
#______________________________________________________________________________________________________________________

def settings_ui(self):
    """ Set object name """
    self.setObjectName('main_settings_widget')
    self.navi_scroll.setObjectName('navi_scroll')
    self.navi_widget.setObjectName('navi_widget')
    self.navi_user_button.setObjectName('navi_user_button')
    self.navi_style_button.setObjectName('navi_style_button')
    self.navi_sound_button.setObjectName('navi_sound_button')
    self.navi_update_button.setObjectName('navi_update_button')
    self.navi_language_button.setObjectName('navi_language_button')
    self.navi_report_button.setObjectName('navi_report_button')
    self.navi_exit_button.setObjectName('navi_exit_button')
    self.panel_right_scroll.setObjectName('panel_right_scroll')
    self.panel_right_widget.setObjectName('panel_right_widget')
    self.user_widget.setObjectName('user_widget')
    self.user_title_label.setObjectName('user_title_label')
    self.user_image_button.setObjectName('user_image_button')
    self.user_info_subtitle_label.setObjectName('user_info_subtitle_label')
    self.user_name_name_label.setObjectName('user_name_name_label')
    self.user_name_content_label.setObjectName('user_name_content_label')
    self.user_email_name_label.setObjectName('user_email_name_label')
    self.user_email_content_label.setObjectName('user_email_content_label')
    self.user_create_date_name_label.setObjectName('user_create_date_name_label')
    self.user_create_date_content_label.setObjectName('user_create_date_content_label')
    self.style_widget.setObjectName('style_widget')
    self.style_title_label.setObjectName('style_title_label')
    self.style_theme_subtitle_label.setObjectName('style_theme_subtitle_label')
    self.style_theme_d_n_name_label.setObjectName('style_theme_d_n_name_label')
    self.style_theme_d_n_content_button.setObjectName('style_theme_d_n_content_button')
    self.style_theme_themes_name_label.setObjectName('style_theme_themes_name_label')
    self.style_theme_themes_content_combobox.setObjectName('style_theme_themes_content_combobox')
    self.sound_widget.setObjectName('sound_widget')
    self.sound_title_label.setObjectName('sound_title_label')
    self.sound_button_name_label.setObjectName('sound_button_name_label')
    self.sound_button_content_button.setObjectName('sound_button_content_button')
    self.sound_alert_name_label.setObjectName('sound_alert_name_label')
    self.sound_alert_content_button.setObjectName('sound_alert_content_button')
    self.sound_notification_name_label.setObjectName('sound_notification_name_label')
    self.sound_notification_content_button.setObjectName('sound_notification_content_button')
    self.update_widget.setObjectName('update_widget')
    self.update_title_label.setObjectName('update_title_label')
    self.update_version_subtitle_label.setObjectName('update_version_subtitle_label')
    self.update_version_description_name_label.setObjectName('update_version_description_name_label')
    self.update_version_description_content_label.setObjectName('update_version_description_content_label')
    self.update_version_changelog_name_label.setObjectName('update_version_changelog_name_label')
    self.update_version_changelog_content_button.setObjectName('update_version_changelog_content_button')
    self.update_options_subtitle_label.setObjectName('update_options_subtitle_label')
    self.update_options_auto_update_name_label.setObjectName('update_options_auto_update_name_label')
    self.update_options_auto_update_content_button.setObjectName('update_options_auto_update_content_button')
    self.update_options_check_update_name_label.setObjectName('update_options_check_update_name_label')
    self.update_options_check_update_content_button.setObjectName('update_options_check_update_content_button')
    self.update_advanced_subtitle_label.setObjectName('update_advanced_subtitle_label')
    self.update_advanced_capacity_name_label.setObjectName('update_advanced_capacity_name_label')
    self.update_advanced_capacity_content_combobox.setObjectName('update_advanced_capacity_content_combobox')
    self.update_advanced_file_verification_name_label.setObjectName('update_advanced_file_verification_name_label')
    self.update_advanced_file_verification_content_button.setObjectName('update_advanced_file_verification_content_label')
    self.language_widget.setObjectName('language_widget')
    self.language_title_label.setObjectName('language_title_label')
    self.language_langauge_name_label.setObjectName('language_langauge_name_label')
    self.language_langauge_content_combobox.setObjectName('language_langauge_content_combobox')
    self.report_widget.setObjectName('report_widget')
    self.report_title_label.setObjectName('report_title_label')
    self.report_auto_report_name_label.setObjectName('report_auto_report_name_label')
    self.report_auto_report_content_button.setObjectName('report_auto_report_content_button')
    self.report_send_report_name_label.setObjectName('report_send_report_name_label')
    self.report_send_report_content_button.setObjectName('report_send_report_content_button')
    """ Set Property """
    self.navi_user_button.setProperty('class', 'navi_button')
    self.navi_style_button.setProperty('class', 'navi_button')
    self.navi_sound_button.setProperty('class', 'navi_button')
    self.navi_update_button.setProperty('class', 'navi_button')
    self.navi_language_button.setProperty('class', 'navi_button')
    self.navi_report_button.setProperty('class', 'navi_button')
    self.user_widget.setProperty('class', 'panel_right_widgets')
    self.style_widget.setProperty('class', 'panel_right_widgets')
    self.sound_widget.setProperty('class', 'panel_right_widgets')
    self.update_widget.setProperty('class', 'panel_right_widgets')
    self.language_widget.setProperty('class', 'panel_right_widgets')
    self.report_widget.setProperty('class', 'panel_right_widgets')
    self.user_title_label.setProperty('class', 'panel_right_titles')
    self.style_title_label.setProperty('class', 'panel_right_titles')
    self.sound_title_label.setProperty('class', 'panel_right_titles')
    self.update_title_label.setProperty('class', 'panel_right_titles')
    self.language_title_label.setProperty('class', 'panel_right_titles')
    self.report_title_label.setProperty('class', 'panel_right_titles')
    self.user_info_subtitle_label.setProperty('class', 'panel_right_subtitles')
    self.style_theme_subtitle_label.setProperty('class', 'panel_right_subtitles')
    self.update_version_subtitle_label.setProperty('class', 'panel_right_subtitles')
    self.update_options_subtitle_label.setProperty('class', 'panel_right_subtitles')
    self.update_advanced_subtitle_label.setProperty('class', 'panel_right_subtitles')
    self.user_name_name_label.setProperty('class', 'panel_right_names')
    self.user_email_name_label.setProperty('class', 'panel_right_names')
    self.user_create_date_name_label.setProperty('class', 'panel_right_names')
    self.style_theme_d_n_name_label.setProperty('class', 'panel_right_names')
    self.style_theme_themes_name_label.setProperty('class', 'panel_right_names')
    self.sound_button_name_label.setProperty('class', 'panel_right_names')
    self.sound_alert_name_label.setProperty('class', 'panel_right_names')
    self.sound_notification_name_label.setProperty('class', 'panel_right_names')
    self.update_version_description_name_label.setProperty('class', 'panel_right_names')
    self.update_version_changelog_name_label.setProperty('class', 'panel_right_names')
    self.update_options_auto_update_name_label.setProperty('class', 'panel_right_names')
    self.update_options_check_update_name_label.setProperty('class', 'panel_right_names')
    self.update_advanced_capacity_name_label.setProperty('class', 'panel_right_names')
    self.update_advanced_file_verification_name_label.setProperty('class', 'panel_right_names')
    self.language_langauge_name_label.setProperty('class', 'panel_right_names')
    self.report_auto_report_name_label.setProperty('class', 'panel_right_names')
    self.report_send_report_name_label.setProperty('class', 'panel_right_names')
    self.user_name_content_label.setProperty('class', 'panel_right_content_label')
    self.user_email_content_label.setProperty('class', 'panel_right_content_label')
    self.user_create_date_content_label.setProperty('class', 'panel_right_content_label')
    self.update_version_description_content_label.setProperty('class', 'panel_right_content_label')
    self.style_theme_d_n_content_button.setProperty('class', 'panel_right_content_button')
    self.sound_button_content_button.setProperty('class', 'panel_right_content_button')
    self.sound_alert_content_button.setProperty('class', 'panel_right_content_button')
    self.sound_notification_content_button.setProperty('class', 'panel_right_content_button')
    self.update_version_changelog_content_button.setProperty('class', 'panel_right_content_button')
    self.update_options_auto_update_content_button.setProperty('class', 'panel_right_content_button')
    self.update_options_check_update_content_button.setProperty('class', 'panel_right_content_button')
    self.update_advanced_file_verification_content_button.setProperty('class', 'panel_right_content_button')
    self.report_auto_report_content_button.setProperty('class', 'panel_right_content_button')
    self.report_send_report_content_button.setProperty('class', 'panel_right_content_button')
    self.style_theme_themes_content_combobox.setProperty('class', 'panel_right_content_combobox')
    self.update_advanced_capacity_content_combobox.setProperty('class', 'panel_right_content_combobox')
    self.language_langauge_content_combobox.setProperty('class', 'panel_right_content_combobox')
    """ Set layout """
    self.main_layout.addWidget(self.navi_scroll, 0, 0, 90, 30)
    self.main_layout.addWidget(self.navi_exit_button, 90, 0, 10, 30)
    self.main_layout.addWidget(self.panel_right_scroll, 0, 30, 100, 70)
    self.main_layout.setSpacing(0)
    self.main_layout.setContentsMargins(0,0,0,0)
    for enc in range(100):
        self.main_layout.setRowStretch(enc, 1)
        self.main_layout.setColumnStretch(enc, 1)
    self.setLayout(self.main_layout)
    self.navi_layout.addWidget(self.navi_user_button)
    self.navi_layout.addWidget(self.navi_style_button)
    self.navi_layout.addWidget(self.navi_sound_button)
    self.navi_layout.addWidget(self.navi_update_button)
    self.navi_layout.addWidget(self.navi_language_button)
    self.navi_layout.addWidget(self.navi_report_button)
    self.navi_layout.setSpacing(0)
    self.navi_layout.setContentsMargins(0,0,0,0)
    self.navi_widget.setLayout(self.navi_layout)
    self.panel_right_layout.addWidget(self.user_widget)
    self.panel_right_layout.addWidget(self.style_widget)
    self.panel_right_layout.addWidget(self.sound_widget)
    self.panel_right_layout.addWidget(self.update_widget)
    self.panel_right_layout.addWidget(self.language_widget)
    self.panel_right_layout.addWidget(self.report_widget)
    self.panel_right_layout.setSpacing(0)
    self.panel_right_layout.setContentsMargins(0,0,0,0)
    self.panel_right_widget.setLayout(self.panel_right_layout)
    self.user_layout.addWidget(self.user_title_label, 0, 0, 1, 100)
    self.user_layout.addWidget(self.user_image_button, 1, 30, 1, 40)
    self.user_layout.addWidget(self.user_info_subtitle_label, 2, 0, 1, 100)
    self.user_layout.addWidget(self.user_name_name_label, 3, 0, 1, 50)
    self.user_layout.addWidget(self.user_name_content_label, 3, 50, 1, 50)
    self.user_layout.addWidget(self.user_email_name_label, 4, 0, 1, 50)
    self.user_layout.addWidget(self.user_email_content_label, 4, 50, 1, 50)
    self.user_layout.addWidget(self.user_create_date_name_label, 5, 0, 1, 50)
    self.user_layout.addWidget(self.user_create_date_content_label, 5, 50, 1, 50)
    self.user_layout.setSpacing(0)
    self.user_layout.setContentsMargins(0,0,0,0)
    for enc in range(100):
        self.user_layout.setColumnStretch(enc, 1)
    self.user_widget.setLayout(self.user_layout)
    self.style_layout.addWidget(self.style_title_label, 0, 0, 1, 100)
    self.style_layout.addWidget(self.style_theme_subtitle_label, 1, 0, 1, 100)
    self.style_layout.addWidget(self.style_theme_d_n_name_label, 2, 0, 1, 50)
    self.style_layout.addWidget(self.style_theme_d_n_content_button, 2, 50, 1, 50)
    self.style_layout.addWidget(self.style_theme_themes_name_label, 3, 0, 1, 50)
    self.style_layout.addWidget(self.style_theme_themes_content_combobox, 3, 50, 1, 50)
    self.style_layout.setSpacing(0)
    self.style_layout.setContentsMargins(0,0,0,0)
    for enc in range(100):
        self.style_layout.setRowStretch(enc, 1)
        self.style_layout.setColumnStretch(enc, 1)
    self.style_widget.setLayout(self.style_layout)
    self.sound_layout.addWidget(self.sound_title_label, 0, 0, 1, 100)
    self.sound_layout.addWidget(self.sound_button_name_label, 1, 0, 1, 50)
    self.sound_layout.addWidget(self.sound_button_content_button, 1, 50, 1, 50)
    self.sound_layout.addWidget(self.sound_alert_name_label, 2, 0, 1, 50)
    self.sound_layout.addWidget(self.sound_alert_content_button, 2, 50, 1, 50)
    self.sound_layout.addWidget(self.sound_notification_name_label, 3, 0, 1, 50)
    self.sound_layout.addWidget(self.sound_notification_content_button, 3, 50, 1, 50)
    self.sound_layout.setSpacing(0)
    self.sound_layout.setContentsMargins(0,0,0,0)
    for enc in range(100):
        self.sound_layout.setRowStretch(enc, 1)
        self.sound_layout.setColumnStretch(enc, 1)
    self.sound_widget.setLayout(self.sound_layout)
    self.update_layout.addWidget(self.update_title_label, 0, 0, 1, 100)
    self.update_layout.addWidget(self.update_version_subtitle_label, 1, 0, 1, 100)
    self.update_layout.addWidget(self.update_version_description_name_label, 2, 0, 1, 50)
    self.update_layout.addWidget(self.update_version_description_content_label, 2, 50, 1, 50)
    self.update_layout.addWidget(self.update_version_changelog_name_label, 3, 0, 1, 50)
    self.update_layout.addWidget(self.update_version_changelog_content_button, 3, 50, 1, 50)
    self.update_layout.addWidget(self.update_options_subtitle_label, 4, 0, 1, 100)
    self.update_layout.addWidget(self.update_options_auto_update_name_label, 5, 0, 1, 50)
    self.update_layout.addWidget(self.update_options_auto_update_content_button, 5, 50, 1, 50)
    self.update_layout.addWidget(self.update_options_check_update_name_label, 6, 0, 1, 50)
    self.update_layout.addWidget(self.update_options_check_update_content_button, 6, 50, 1, 50)
    self.update_layout.addWidget(self.update_advanced_subtitle_label, 7, 0, 1, 100)
    self.update_layout.addWidget(self.update_advanced_capacity_name_label, 8, 0, 1, 50)
    self.update_layout.addWidget(self.update_advanced_capacity_content_combobox, 8, 50, 1, 50)
    self.update_layout.addWidget(self.update_advanced_file_verification_name_label, 9, 0, 1, 50)
    self.update_layout.addWidget(self.update_advanced_file_verification_content_button, 9, 50, 1, 50)
    self.update_layout.setSpacing(0)
    self.update_layout.setContentsMargins(0,0,0,0)
    for enc in range(100):
        self.update_layout.setRowStretch(enc, 1)
        self.update_layout.setColumnStretch(enc, 1)
    self.update_widget.setLayout(self.update_layout)
    self.language_layout.addWidget(self.language_title_label, 0, 0, 1, 100)
    self.language_layout.addWidget(self.language_langauge_name_label, 2, 0, 1, 50)
    self.language_layout.addWidget(self.language_langauge_content_combobox, 2, 50, 1, 50)
    self.language_layout.setSpacing(0)
    self.language_layout.setContentsMargins(0,0,0,0)
    for enc in range(100):
        self.language_layout.setRowStretch(enc, 1)
        self.language_layout.setColumnStretch(enc, 1)
    self.language_widget.setLayout(self.language_layout)
    self.report_layout.addWidget(self.report_title_label, 0, 0, 1, 100)
    self.report_layout.addWidget(self.report_auto_report_name_label, 1, 0, 1, 50)
    self.report_layout.addWidget(self.report_auto_report_content_button, 1, 50, 1, 50)
    self.report_layout.addWidget(self.report_send_report_name_label, 2, 0, 1, 50)
    self.report_layout.addWidget(self.report_send_report_content_button, 2, 50, 1, 50)
    self.report_layout.setSpacing(0)
    self.report_layout.setContentsMargins(0,0,0,0)
    for enc in range(100):
        self.report_layout.setRowStretch(enc, 1)
        self.report_layout.setColumnStretch(enc, 1)
    self.report_widget.setLayout(self.report_layout)
    """ Set widget"""
    self.setHidden(False)
    self.user_widget.setHidden(True)
    self.style_widget.setHidden(True)
    self.sound_widget.setHidden(True)
    self.update_widget.setHidden(True)
    self.language_widget.setHidden(True)
    self.report_widget.setHidden(True)
    self.navi_scroll.setWidgetResizable(True)
    self.navi_scroll.setWidget(self.navi_widget)
    self.panel_right_scroll.setWidgetResizable(True)
    self.panel_right_scroll.setWidget(self.panel_right_widget)
    self.navi_user_button.setDisabled(True)
    self.navi_update_button.setDisabled(True)
    self.navi_report_button.setDisabled(True)
    """ Set label """
    self.user_title_label.setAlignment(Qt.AlignCenter)
    self.user_info_subtitle_label.setAlignment(Qt.AlignCenter)
    self.user_name_name_label.setAlignment(Qt.AlignCenter)
    self.user_name_content_label.setAlignment(Qt.AlignCenter)
    self.user_email_name_label.setAlignment(Qt.AlignCenter)
    self.user_email_content_label.setAlignment(Qt.AlignCenter)
    self.user_create_date_name_label.setAlignment(Qt.AlignCenter)
    self.user_create_date_content_label.setAlignment(Qt.AlignCenter)
    self.style_title_label.setAlignment(Qt.AlignCenter)
    self.style_theme_subtitle_label.setAlignment(Qt.AlignCenter)
    self.style_theme_d_n_name_label.setAlignment(Qt.AlignCenter)
    self.style_theme_themes_name_label.setAlignment(Qt.AlignCenter)
    self.sound_title_label.setAlignment(Qt.AlignCenter)
    self.sound_button_name_label.setAlignment(Qt.AlignCenter)
    self.sound_alert_name_label.setAlignment(Qt.AlignCenter)
    self.sound_notification_name_label.setAlignment(Qt.AlignCenter)
    self.update_title_label.setAlignment(Qt.AlignCenter)
    self.update_version_subtitle_label.setAlignment(Qt.AlignCenter)
    self.update_version_description_name_label.setAlignment(Qt.AlignCenter)
    self.update_version_description_content_label.setAlignment(Qt.AlignCenter)
    self.update_version_changelog_name_label.setAlignment(Qt.AlignCenter)
    self.update_options_subtitle_label.setAlignment(Qt.AlignCenter)
    self.update_options_auto_update_name_label.setAlignment(Qt.AlignCenter)
    self.update_options_check_update_name_label.setAlignment(Qt.AlignCenter)
    self.update_advanced_subtitle_label.setAlignment(Qt.AlignCenter)
    self.update_advanced_capacity_name_label.setAlignment(Qt.AlignCenter)
    self.update_advanced_file_verification_name_label.setAlignment(Qt.AlignCenter)
    self.language_title_label.setAlignment(Qt.AlignCenter)
    self.language_langauge_name_label.setAlignment(Qt.AlignCenter)
    self.report_title_label.setAlignment(Qt.AlignCenter)
    self.report_auto_report_name_label.setAlignment(Qt.AlignCenter)
    self.report_send_report_name_label.setAlignment(Qt.AlignCenter)
    """ Set size"""
    self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.navi_scroll.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.navi_widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.navi_user_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.navi_style_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.navi_sound_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.navi_update_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.navi_language_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.navi_report_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.navi_exit_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.panel_right_scroll.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.panel_right_widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.user_widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.user_title_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.user_image_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.user_info_subtitle_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.user_name_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.user_name_content_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.user_email_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.user_email_content_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.user_create_date_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.user_create_date_content_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.style_widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.style_title_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.style_theme_subtitle_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.style_theme_d_n_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.style_theme_d_n_content_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.style_theme_themes_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.style_theme_themes_content_combobox.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.sound_widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.sound_title_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.sound_button_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.sound_button_content_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.sound_alert_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.sound_alert_content_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.sound_notification_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.sound_notification_content_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.update_widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.update_title_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.update_version_subtitle_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.update_version_description_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.update_version_description_content_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.update_version_changelog_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.update_version_changelog_content_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.update_options_subtitle_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.update_options_auto_update_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.update_options_auto_update_content_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.update_options_check_update_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.update_options_check_update_content_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.update_advanced_subtitle_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.update_advanced_capacity_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.update_advanced_capacity_content_combobox.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.update_advanced_file_verification_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.update_advanced_file_verification_content_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.language_widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.language_title_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.language_langauge_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.language_langauge_content_combobox.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.report_widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.report_title_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.report_auto_report_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.report_auto_report_content_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.report_send_report_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.report_send_report_content_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    """ Set item in combo box """
    self.style_theme_themes_content_combobox.addItem('Vintage elegance light')
    self.style_theme_themes_content_combobox.addItem('Vintage elegance dark')
    self.update_advanced_capacity_content_combobox.addItem('500 KB/s')
    self.update_advanced_capacity_content_combobox.addItem('1000 KB/s')
    self.update_advanced_capacity_content_combobox.addItem('2000 KB/s')
    self.update_advanced_capacity_content_combobox.addItem('5000 KB/s')
    self.update_advanced_capacity_content_combobox.addItem('UNLIMITED')
    self.language_langauge_content_combobox.addItem("English / English")
    self.language_langauge_content_combobox.addItem("Polski / Polish")
#______________________________________________________________________________________________________________________

def settings_reload_style(self):
    _global_config = json.load(open(self.main_path+'/CONFIG/GLOBAL/global_config.json', 'r'))
    self.setStyleSheet(open(str(self.main_path+'/STYLE/CSS/settings/'+_global_config['theme']+'.css')).read())
    self.navi_exit_button.setIcon(QIcon(load_svg(str(self.main_path+'/STYLE/IMG/icons/main/exit_'+_global_config['theme']+'.svg'), 256, 256)))
    self.navi_exit_button.setIconSize(self.navi_exit_button.size())
#______________________________________________________________________________________________________________________

def settings_retranslate(self):
    _global_config = json.load(open(self.main_path+'/CONFIG/GLOBAL/global_config.json', 'r'))
    _t = json.load(open(self.main_path+'/CONFIG/settings/translate.json', 'r'))
    _l = _global_config['language']
    _m = _global_config['theme'] 
    self.navi_user_button.setText(_t['navi_user_button'][_l])
    self.navi_style_button.setText(_t['navi_style_button'][_l])
    self.navi_sound_button.setText(_t['navi_sound_button'][_l])
    self.navi_update_button.setText(_t['navi_update_button'][_l])
    self.navi_language_button.setText(_t['navi_language_button'][_l])
    self.navi_report_button.setText(_t['navi_report_button'][_l])
    self.user_title_label.setText(_t['user_title_label'][_l])
    self.user_info_subtitle_label.setText(_t['user_info_subtitle_label'][_l])
    self.user_name_name_label.setText(_t['user_name_name_label'][_l])
    self.user_email_name_label.setText(_t['user_email_name_label'][_l])
    self.user_create_date_name_label.setText(_t['user_create_date_name_label'][_l])
    self.style_title_label.setText(_t['style_title_label'][_l])
    self.style_theme_subtitle_label.setText(_t['style_theme_subtitle_label'][_l])
    self.style_theme_d_n_name_label.setText(_t['style_theme_d_n_name_label'][_l])
    self.style_theme_d_n_content_button.setText(_t['style_theme_d_n_content_button'][_l][1])
    self.style_theme_themes_name_label.setText(_t['style_theme_themes_name_label'][_l])
    self.sound_title_label.setText(_t['sound_title_label'][_l])
    self.sound_button_name_label.setText(_t['sound_button_name_label'][_l])
    self.sound_button_content_button.setText(_t['sound_button_content_button'][_l][0])
    self.sound_alert_name_label.setText(_t['sound_alert_name_label'][_l])
    self.sound_alert_content_button.setText(_t['sound_alert_content_button'][_l][0])
    self.sound_notification_name_label.setText(_t['sound_notification_name_label'][_l])
    self.sound_notification_content_button.setText(_t['sound_notification_content_button'][_l][0])
    self.update_title_label.setText(_t['update_title_label'][_l])
    self.update_version_subtitle_label.setText(_t['update_version_subtitle_label'][_l])
    self.update_version_description_name_label.setText(_t['update_version_description_name_label'][_l])
    self.update_version_changelog_name_label.setText(_t['update_version_changelog_name_label'][_l])
    self.update_version_changelog_content_button.setText(_t['update_version_changelog_content_button'][_l])
    self.update_options_subtitle_label.setText(_t['update_options_subtitle_label'][_l])
    self.update_options_auto_update_name_label.setText(_t['update_options_auto_update_name_label'][_l])
    self.update_options_auto_update_content_button.setText(_t['update_options_auto_update_content_button'][_l][0])
    self.update_options_check_update_name_label.setText(_t['update_options_check_update_name_label'][_l])
    self.update_options_check_update_content_button.setText(_t['update_options_check_update_content_button'][_l][0])
    self.update_advanced_subtitle_label.setText(_t['update_advanced_subtitle_label'][_l])
    self.update_advanced_capacity_name_label.setText(_t['update_advanced_capacity_name_label'][_l])
    self.update_advanced_file_verification_name_label.setText(_t['update_advanced_file_verification_name_label'][_l])
    self.update_advanced_file_verification_content_button.setText(_t['update_advanced_file_verification_content_label'][_l])
    self.language_title_label.setText(_t['language_title_label'][_l])
    self.language_langauge_name_label.setText(_t['language_langauge_name_label'][_l])
    self.report_title_label.setText(_t['report_title_label'][_l])
    self.report_auto_report_name_label.setText(_t['report_auto_report_name_label'][_l])
    self.report_auto_report_content_button.setText(_t['report_auto_report_content_button'][_l][0])
    self.report_send_report_name_label.setText(_t['report_send_report_name_label'][_l])
    self.report_send_report_content_button.setText(_t['report_send_report_content_button'][_l])
#______________________________________________________________________________________________________________________

def load_svg(svg_path, width, height):
    renderer = QSvgRenderer(svg_path)
    pixmap = QPixmap(width, height)
    pixmap.fill(Qt.transparent)
    painter = QPainter(pixmap)
    renderer.render(painter)
    painter.end()
    scaled_pixmap = pixmap.scaled(QSize(width, height), Qt.KeepAspectRatio, Qt.SmoothTransformation)
    return scaled_pixmap
#______________________________________________________________________________________________________________________
